- name : DEMO on advanced loops
  hosts : DEV
  become : yes
  tasks :
    - name : advanced loop
      yum :
        name : "{{item.name}}"
        state : "{{item.state}}"
      with_items :
        - { name : 'httpd', state : 'latest'}
        - { name : 'httpd-devel', state : 'absent'}